name: Release
on: [push, pull_request]

jobs:
  test:
    name: Test @ NodeJS - x86 - ubuntu-latest
    # Support [skip ci] out of box with github actions Workaround
    # Only works for push https://github.com/actions/runner/issues/774
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && contains(toJson(github.event.commits), '[skip ci]') == false)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS LTS
        uses: actions/setup-node@v2
      - name: Build & Validation
        run: |
          npm prune && npm i
          npm run build
          npm run lint
          npm run test
  release:
    name: Release @ NodeJS LTS - x86 - ubuntu-latest
    runs-on: ubuntu-latest
    needs:
      - test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup NodeJS LTS
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: |
          npm prune && npm i
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        # TODO move npm run documentation to semantic-release
        run: |
          npm run build
          npm run documentation
          npx semantic-release
